# Generated by Django 4.2 on 2025-07-28 06:56

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable='', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('profile_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_joined', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groups', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_active', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_staff', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_superuser', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_login', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_permissions', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecordsModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('clock_out', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hrs_now', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('total_hrs', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('touserid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('usermessage', models.CharField(blank=True, default='', max_length=999999, null=True)),
                ('date_send', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeInOutClock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable='', primary_key=True, serialize=False)),
                ('userID', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time_in', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time_out', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('hrs', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time_in_description', models.CharField(blank=True, default='', max_length=100)),
                ('time_out_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time_in_location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time_out_location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
