# Generated by Django 4.2 on 2025-08-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='userid',
            new_name='fromuserid',
        ),
    ]
