# Generated by Django 4.2 on 2025-08-30 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_userid_chatmodel_fromuserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=999999, null=True)),
                ('date_send', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
