# Generated by Django 4.2 on 2025-08-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='message',
            field=models.JSONField(default=list),
        ),
    ]
