# Generated by Django 4.2 on 2025-08-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='fromuserid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
