# Generated by Django 4.2 on 2025-09-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_conversation_fromuserid_conversation_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='isUser',
            field=models.BooleanField(blank=True, default='', max_length=4, null=True),
        ),
    ]
