# Generated by Django 4.2 on 2025-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_chatmodel_isuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
