# Generated by Django 4.2 on 2025-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_usermodel_bio_usermodel_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_url',
            field=models.CharField(blank=True, default='', max_length=9999, null=True),
        ),
    ]
